fields:
  to_flatten:
    top_level:
      - id
      - agg_is_shown_at
      - agg_is_shown_by
      - agg_preview
    web_resources:
      - agg_is_shown_at
      - agg_is_shown_by
      - agg_preview
      - agg_has_view
acceptable_bcp47_codes:
  - ar-Arab
  - ar-Latn
  - en
  - fa-Arab
  - fa-Latn
  - fr
  - tr
defaults:
  base_data_dir: 'data'
  data_dir: ''
  mapping_file: 'config/metadata_mapping.json'
  traject_dir: 'traject_configs'
number_of_configs_to_test: 1
